name: Auto Submodule Setup

on:
  push:
    paths:
      - '**/project.json'
      - 'setup_submodules.sh'

jobs:
  run-setup-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          submodules: false

      - name: Install dependencies (gh, jq, git-flow)
        run: |
          sudo apt update
          sudo apt install -y gh jq git-flow

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GH_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Run setup_submodules.sh
        run: |
          bash ./setup_submodules.sh

      - name: Commit & Push if needed
        run: |
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-update submodules"
          git push